version: "3.2"
services:
    nginx:
      image: nginx
      restart: always
      volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./app:/usr/share/nginx/html
      ports:
        - "80:80"
      depends_on:
        - php

    php:
      build:
        context: .
        dockerfile: ./docker/php/Dockerfile
        args:
          user: $USER
      restart: always
      volumes:
        - ./app:/usr/share/nginx/html
      expose:
        - "9000"

    pgsql:
      image: postgres
      restart: always
      environment:
        POSTGRES_DB: test
        POSTGRES_USER: main
        POSTGRES_PASSWORD: example