version: "3.2"
services:
    nginx:
      image: nginx
      restart: always
      volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./app:/usr/share/nginx/html
      ports:
        - "80:80"

    php:
      build: ./docker/php
      restart: always
      expose:
        - "9000"
      volumes:
        - ./app:/usr/share/nginx/html

    pgsql:
      image: postgres
      restart: always
      environment:
        POSTGRES_DB: test
        POSTGRES_USER: root
        POSTGRES_PASSWORD: example
